<?php $page_title = $page_title ?? 'JobPortal'; $base_path = $base_path ?? ''; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= htmlspecialchars($page_title) ?> | JobPortal</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?= $base_path ?>css/style.css" rel="stylesheet"></head><body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm"><div class="container"><a class="navbar-brand fw-bold" href="<?= $base_path ?>index.php">JobPortal</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div id="nav" class="collapse navbar-collapse"><ul class="navbar-nav ms-auto align-items-lg-center">
<?php if (!empty($_SESSION['user']) && $_SESSION['user']['role'] === 'student'): ?><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>student/dashboard.php">Dashboard</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>student/jobs.php">Jobs</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>student/saved-jobs.php">Saved Jobs</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>student/profile.php">Profile</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>student/logout.php">Logout</a></li>
<?php elseif (!empty($_SESSION['user']) && $_SESSION['user']['role'] === 'admin'): ?><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>admin/dashboard.php">Admin Dashboard</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>admin/feedback.php">Feedback</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>admin/reports.php">Reports</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>admin/logout.php">Logout</a></li>
<?php else: ?><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>about.php">About</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>features.php">Features</a></li><li class="nav-item"><a class="nav-link" href="<?= $base_path ?>contact.php">Contact</a></li><li class="nav-item"><a class="btn btn-light btn-sm ms-lg-2" href="<?= $base_path ?>login.php">Login</a></li><?php endif; ?>
</ul></div></div></nav><main>
<?php if (!empty($_SESSION['flash'])) foreach ($_SESSION['flash'] as $message): ?><div class="container mt-3"><div class="alert alert-info mb-0"><?= htmlspecialchars($message) ?></div></div><?php endforeach; unset($_SESSION['flash']); ?>
